name: Push [Master]

on:
  push:
    branches:
      - master

jobs:
  apiandbackoffice:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: sleep 10s
        run: |
          sleep 10s
