name: Push [Master]

on:
  push:
    branches:
      - master

jobs:
  apiandbackoffice:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: sleep 3m
        run: |
          sleep 3m
  dummyjob:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Send custom variable to Meercode Build
        uses: meercodeio/meercode-custom-variable@0.0.2
        with:
          meercode-token: ${{ secrets.MEERCODE_TOKEN }}
          url: "https://meercode.io/test"

      - name: sleep
        run: |
          sleep 30s

  dummyjobWithFailStepButOk:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: fail
        continue-on-error: true
        run: |
          asdasdas
      - name: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy
        run: |
          sleep 30s
