name: Push [test-reporter]

on:
  push:
    branches:
      - test-reporter

jobs:
  test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd awesome-app
          npm ci
          npm test 
          ls
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: awesome-app/reports/jest-*.xml
          reporter: jest-junit